# Base image
FROM node:23.11-slim AS base

# Declare build-time arguments
ARG COMPANY_NAME
ARG TWITTER_CREATOR
ARG TWITTER_SITE
ARG SITE_NAME

ARG PAYLOAD_PUBLIC_SERVER_URL
ARG NEXT_PUBLIC_SERVER_URL

ARG PAYLOAD_PUBLIC_DRAFT_SECRET
ARG NEXT_PRIVATE_DRAFT_SECRET

ARG PAYLOAD_SECRET
ARG NEXT_PRIVATE_SECRET

ARG POSTGRES_URL
ARG BLOB_READ_WRITE_TOKEN

ARG REVALIDATION_KEY
ARG NEXT_PRIVATE_REVALIDATION_KEY

ARG SMTP_FROM_NAME
ARG SMTP_FROM_ADDRESS
ARG SMTP_HOST
ARG SMTP_PORT
ARG SMTP_USER
ARG SMTP_PASS
ARG ADMIN_EMAIL

# Allow ARGs to be passed at build time
ENV COMPANY_NAME=${COMPANY_NAME}
ENV TWITTER_CREATOR=${TWITTER_CREATOR}
ENV TWITTER_SITE=${TWITTER_SITE}
ENV SITE_NAME=${SITE_NAME}

ENV PAYLOAD_PUBLIC_SERVER_URL=${PAYLOAD_PUBLIC_SERVER_URL}
ENV NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}

ENV PAYLOAD_PUBLIC_DRAFT_SECRET=${PAYLOAD_PUBLIC_DRAFT_SECRET}
ENV NEXT_PRIVATE_DRAFT_SECRET=${NEXT_PRIVATE_DRAFT_SECRET}

ENV PAYLOAD_SECRET=${PAYLOAD_SECRET}
ENV NEXT_PRIVATE_SECRET=${NEXT_PRIVATE_SECRET}

ENV POSTGRES_URL=${POSTGRES_URL}
ENV BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN}

ENV REVALIDATION_KEY=${REVALIDATION_KEY}
ENV NEXT_PRIVATE_REVALIDATION_KEY=${NEXT_PRIVATE_REVALIDATION_KEY}

ENV SMTP_FROM_NAME=${SMTP_FROM_NAME}
ENV SMTP_FROM_ADDRESS=${SMTP_FROM_ADDRESS}
ENV SMTP_HOST=${SMTP_HOST}
ENV SMTP_PORT=${SMTP_PORT}
ENV SMTP_USER=${SMTP_USER}
ENV SMTP_PASS=${SMTP_PASS}
ENV ADMIN_EMAIL=${ADMIN_EMAIL}

# Builder stage
FROM base AS builder

WORKDIR /home/node/app

# Copy package files and install dependencies
COPY package*.json ./
RUN yarn install

# Copy source code and build
COPY . .
RUN yarn build

# Runtime stage
FROM base AS runtime

# Declare build-time arguments
ARG COMPANY_NAME
ARG TWITTER_CREATOR
ARG TWITTER_SITE
ARG SITE_NAME

ARG PAYLOAD_PUBLIC_SERVER_URL
ARG NEXT_PUBLIC_SERVER_URL

ARG PAYLOAD_PUBLIC_DRAFT_SECRET
ARG NEXT_PRIVATE_DRAFT_SECRET

ARG PAYLOAD_SECRET
ARG NEXT_PRIVATE_SECRET

ARG POSTGRES_URL
ARG BLOB_READ_WRITE_TOKEN

ARG REVALIDATION_KEY
ARG NEXT_PRIVATE_REVALIDATION_KEY

ARG SMTP_FROM_NAME
ARG SMTP_FROM_ADDRESS
ARG SMTP_HOST
ARG SMTP_PORT
ARG SMTP_USER
ARG SMTP_PASS
ARG ADMIN_EMAIL

# Allow ARGs to be passed at build time
ENV COMPANY_NAME=${COMPANY_NAME}
ENV TWITTER_CREATOR=${TWITTER_CREATOR}
ENV TWITTER_SITE=${TWITTER_SITE}
ENV SITE_NAME=${SITE_NAME}

ENV PAYLOAD_PUBLIC_SERVER_URL=${PAYLOAD_PUBLIC_SERVER_URL}
ENV NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}

ENV PAYLOAD_PUBLIC_DRAFT_SECRET=${PAYLOAD_PUBLIC_DRAFT_SECRET}
ENV NEXT_PRIVATE_DRAFT_SECRET=${NEXT_PRIVATE_DRAFT_SECRET}

ENV PAYLOAD_SECRET=${PAYLOAD_SECRET}
ENV NEXT_PRIVATE_SECRET=${NEXT_PRIVATE_SECRET}

ENV POSTGRES_URL=${POSTGRES_URL}
ENV BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN}

ENV REVALIDATION_KEY=${REVALIDATION_KEY}
ENV NEXT_PRIVATE_REVALIDATION_KEY=${NEXT_PRIVATE_REVALIDATION_KEY}

ENV SMTP_FROM_NAME=${SMTP_FROM_NAME}
ENV SMTP_FROM_ADDRESS=${SMTP_FROM_ADDRESS}
ENV SMTP_HOST=${SMTP_HOST}
ENV SMTP_PORT=${SMTP_PORT}
ENV SMTP_USER=${SMTP_USER}
ENV SMTP_PASS=${SMTP_PASS}
ENV ADMIN_EMAIL=${ADMIN_EMAIL}
ENV NODE_ENV=production

WORKDIR /home/node/app

# Copy only what is needed for production
COPY package*.json ./
RUN yarn install --production

# Copy built app from builder stage
COPY --from=builder /home/node/app/dist ./dist

# If your app needs public assets or config, copy them too
COPY --from=builder /home/node/app/public ./public
COPY --from=builder /home/node/app/config ./config

EXPOSE 3000

CMD ["node", "dist/server.js"]